language: scala

services:
  - docker

jdk: openjdk11

scala:
   - 2.13.1

before_script:
  - docker login --username ${DOCKER_USER} --password "${DOCKER_PASSWORD}"

script:
  - sbt compile docker:publish
