language: scala

services:
  - docker

jdk: openjdk11

scala:
   - 2.13.1

before_script:
  - set
  - echo "${DOCKER_PASSWORD}"
  - echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USER} --password-stdin

script:
  - sbt compile
  - sbt docker:publish
