name: v_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - master

pool: 'hetzner03'

steps:
  - task: Bash@3
    displayName: Show kubernetes stats
    inputs:
      targetType: 'inline'
      script: |
        kubectl cluster-info

  - task: Bash@2
    displayName: Prepare dockerfile for image
    inputs:
      targetType: 'inline'
      script: |
        docker run -i -t -v $(Build.SourcesDirectory):/root --rm hseeberger/scala-sbt:graalvm-ce-20.0.0-java11_1.3.13_2.13.3 sbt -Divy.home=data/cache/agent/.ivy2 -Dsbt.ivy.home=/data/cache/agent/.ivy2 compile docker:stage

  - task: Docker@2
    displayName: Build the image
    inputs:
      workingDirectory: $(Build.SourcesDirectory)
      repository: eblovich/bnlsusanin-bot
      command: buildAndPush
      dockerfile: '$(Build.SourcesDirectory)/target/docker/Dockerfile'
      tags: $(Build.BuildNumber)

  - task: Bash@3
    displayName: Deploy app
    inputs:
      workingDirectory: $(Build.SourcesDirectory)
      targetType: 'inline'
      script: |
        set
        # cat config.yml | envsubst | kubectl apply -f -
        cat deployment.yml | sed "s#APP_VERSION#$(Build.BuildNumber)#g" | kubectl apply -f -
#    env:
#      DATABASE_PASSWORD: $(TELEGRAM_TOKEN)
#      MINIO_SECRET_KEY: $(GEONAMES_USER_ID)
