openapi: 3.0.1
info:
  title: Geonames API
  version: "1.0"
  description: API's for working with genonames database

paths:
  /searchJSON:
    get:
      summary: Returns list of cities matching keyword
      operationId: api.geonames.search
      parameters:
        - name: q
          in: query
          required: true
          description: keyword to be matched
          schema:
            type: string
        - name: username
          in: query
          required: true
          description: Username (API key)
          schema:
            type: string
      responses:
        "200":
          description: List of cities that look like 'q'
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/Result"
servers:
  - url: http://api.geonames.org/
components:
  schemas:
    Result:
      type: object
      properties:
        totalResultsCount:
          required: true
          type: integer
          format: int64
        geonames:
          items:
            $ref: "#/components/schemas/Item"
      required:
      - totalResultsCount
      - geonames
    Item:
      type: object
      properties:
        geonameId:
          type: integer
          format: int64
        toponymName:
          type: string
        countryName:
          type: string
        lat:
          type: string
        lng:
          type: string
      required:
      - geonameId
      - toponymName
      - lat
      - lng